version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tfg_postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tfg_pgadmin
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
